In [13]:
import pandas as pd

df_res = pd.read_csv("/home/hermann/projeto_soft_sensor/data/processed/resultado_otimizacao_pls.csv")
# df_res.columns = ['indice', 'EMA_Span',	'Derivadas','Rolling','Roll_Window','Squared','N_Features','Best_C','RMSE','R2','Jarque_Bera_Stat','Jarque_Bera_p']

# 2. Calcular a Razão de Compressão do Espaço de Estados (C / Features)
df_res['Razao_C_F'] = df_res['Best_C'] / df_res['N_Features']

df_res.sort_values(by="R2", ascending = False)

df_res[ (df_res['Jarque_Bera_p'] >= 0.05) & (df_res['Razao_C_F'] <=0.40) ][['Razao_C_F','N_Features','Best_C','R2','Jarque_Bera_p','EMA_Span',	'Derivadas','Rolling','Roll_Window']].sort_values(by='R2', ascending=False).head(20)

,Razao_C_F,N_Features,Best_C,R2,Jarque_Bera_p,EMA_Span,Derivadas,Rolling,Roll_Window
0,0.388889,36,14,0.988627,0.187688,15,True,True,18.0
4,0.388889,36,14,0.987683,0.453794,21,True,True,16.0
5,0.388889,36,14,0.987126,0.861092,18,True,True,18.0
8,0.388889,36,14,0.986938,0.447158,21,True,True,18.0
19,0.388889,36,14,0.985833,0.528146,27,True,True,14.0
24,0.388889,36,14,0.985575,0.760718,24,True,True,16.0
37,0.388889,36,14,0.984687,0.357534,24,True,True,18.0
44,0.344828,29,10,0.983981,0.490004,12,True,True,18.0
51,0.388889,36,14,0.983510,0.061893,27,True,True,18.0
98,0.275862,29,8,0.978957,0.086949,9,True,True,18.0
109,0.275862,29,8,0.978310,0.069709,21,False,True,16.0
119,0.363636,22,8,0.977649,0.177755,15,False,True,16.0
124,0.275862,29,8,0.977385,0.075644,18,False,True,18.0
125,0.275862,29,8,0.977373,0.488376,6,True,True,18.0
131,0.275862,29,8,0.977006,0.072700,27,False,True,16.0
133,0.222222,36,8,0.976805,0.087442,12,True,True,18.0
138,0.275862,29,8,0.976602,0.170331,18,False,True,16.0
139,0.275862,29,8,0.976553,0.304333,15,False,True,16.0
140,0.222222,36,8,0.976517,0.324228,9,True,True,18.0
147,0.275862,29,8,0.976098,0.267843,15,False,True,18.0

In [15]:
import pandas as pd

df_res_mwpls = pd.read_csv("/home/hermann/projeto_soft_sensor/data/processed/resultado_otimizacao_mwpls.csv")
# df_res.columns = ['indice', 'EMA_Span',	'Derivadas','Rolling','Roll_Window','Squared','N_Features','Best_C','RMSE','R2','Jarque_Bera_Stat','Jarque_Bera_p']

# 2. Calcular a Razão de Compressão do Espaço de Estados (C / Features)
df_res_mwpls['Razao_C_F'] = df_res_mwpls['Components_C'] / df_res_mwpls['N_Features']

df_res_mwpls.sort_values(by="R2", ascending = False)

#df_res[df_res['Jarque_Bera_p'] >= 0.05].sort_values(by='R2', ascending=False)
df_res_mwpls[ (df_res_mwpls['Jarque_Bera_p'] >= 0.05) & (df_res_mwpls['Razao_C_F'] <=0.35) ][['Razao_C_F','MW_Window','N_Features','Components_C','R2','Jarque_Bera_p','Lag_Reflux_Flow','Lag_Flow_To_Next_Process']].sort_values(by='R2', ascending=False).head(20)

,Razao_C_F,MW_Window,N_Features,Components_C,R2,Jarque_Bera_p,Lag_Reflux_Flow,Lag_Flow_To_Next_Process
456,0.344828,300,29,10,0.986527,0.194407,2,17
583,0.333333,400,36,12,0.985290,0.143066,2,16
608,0.333333,400,36,12,0.985081,0.084150,3,18
613,0.333333,400,36,12,0.985041,0.521000,3,18
652,0.344828,400,29,10,0.984572,0.057937,2,16
659,0.333333,400,36,12,0.984431,0.325392,2,16
675,0.333333,400,36,12,0.984239,0.142384,4,19
679,0.333333,400,36,12,0.984212,0.741455,3,18
701,0.333333,400,36,12,0.984055,0.627311,2,17
706,0.333333,400,36,12,0.984014,0.062193,5,21
717,0.333333,400,36,12,0.983916,0.205084,5,21
734,0.344828,400,29,10,0.983715,0.911360,2,16
744,0.344828,300,29,10,0.983652,0.118510,3,18
755,0.344828,400,29,10,0.983581,0.215058,2,17
765,0.333333,400,36,12,0.983508,0.561172,3,18
772,0.333333,400,36,12,0.983449,0.270594,4,19
782,0.344828,400,29,10,0.983381,0.094003,2,17
787,0.333333,400,36,12,0.983347,0.403136,2,17
797,0.344828,400,29,10,0.983244,0.163421,3,18
822,0.344828,400,29,10,0.983023,0.121701,3,18